---
# Default values for microservice.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  replicaCount: 1
  environment: {}
   # list of key: value
   # GLOBAL1: value
 
image:
  repository: "crccheck/hello-world"
  tag: "latest"
  pullPolicy: IfNotPresent

  #replicaCount: 1

nameOverride: ""
fullnameOverride: ""


# serviceAccount: 

# Annotation for the Deployment
annotations: {}

# List of services
services:
  - name: web
    type: ClusterIP
    annotations: {}
    specs:
    - port: 8000
      targetPort: 8000
      name: http

environment: {}
#   VAR1: value1

volumes:
  enabled: false
  pvc:
    enabled: false
    existing_claim:
    name: pvc
    mountPath: /pv
    size: 1G
    class:
    accessModes:
      - ReadWriteOnce

  configMaps:
#    - name: test
#      mountPath: /test
#      data:
#        test.conf: |
#          hello

## Configure Ingress based on the documentation here: https://kubernetes.io/docs/concepts/services-networking/ingress/
##
ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      servicePort: 8000
      serviceName: web
      path: /
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  limits:
    cpu: 2
    memory: 2000Mi
  requests:
    cpu: 500m
    memory: 500Mi